### ISSUE TITLE
user-secret can't find Microsoft.Framework.ApplicationHost

### ISSUE THREAD

**Issue by damccull** [aspnet/UserSecrets#39]
Trying to use SecretManager with beta7. It reports installing perfectly, but when running I get the following error. @davidfowl said the package was renamed to something else and I assume that's why it's failing.

```
PM> dnu commands install secretmanager
***Good to go***

PM> user-secret -h
user-secret.cmd : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ApplicationHost' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ user-secret.cmd
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.IO.FileN...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
File name: 'Microsoft.Framework.ApplicationHost'
   at System.Reflection.Runtime
Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean 
suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, 
Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by BrennanConroy** [comment]
dnu commands install Microsoft.Framework.SecretManager

**Comment by muratg** [comment]
Yup, there was a rename.  We just now posted on Announcements (https://github.com/aspnet/Announcements/issues/64) about this change, so closing this one.
