### ISSUE TITLE
secrets manager doesn't work from windows VSCode

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/UserSecrets#59]
We should throw a better error message .
Two customers confirm this. 
I can confirm that the same code on Mac/vscode work but on Windows/vscode it doesn't.

From: Daniel Roth
Any idea what could be going on with this customer reported issue with VSCode and user secrets?:
 
I have a project setup to use secret and if I run the project in VS15 or cmd using "dnx web" work but if I run it from VSCode Command Palette -> dnx:Run Command -> dnx web I get the following error:

``` 
Application startup exception: System.ArgumentNullException: Value cannot be null.
Parameter name: paths
at System.IO.Path.Combine(String[] paths)
at Microsoft.Extensions.Configuration.UserSecrets.PathHelper.GetSecretsPathFromSecretsId(String userSecretsId)
at Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration)
at aspnet.Startup..ctor(IHostingEnvironment env) in c:\Users\rspaulino\Documents\vscodeprojects\aspnet\Startup.cs:lin
e 23
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider pro
vider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanc
eType, Object[] parameters)
at Microsoft.AspNet.Hosting.Startup.StartupLoader.LoadMethods(Type startupType, IList`1 diagnosticMessages)
at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
Hosting environment: Development
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

From: Glenn Condron 
Environment.GetEnvironmentVariable("APPDATA”) is null for some reason?

See: https://github.com/aspnet/UserSecrets/blob/dev/src/Microsoft.Extensions.Configuration.UserSecrets/PathHelper.cs#L61

**Comment by Rick-Anderson** [comment]
Customer reports -  Thanks for the suggestion [make sure APPDATA is set] but as you can see in the screenshot APPDATA and user-secret are working fine for the project, let me know if you want me to run some command to get more data.

**Comment by muratg** [comment]
@BrennanConroy Could you try a repro when you get the chance?

cc @glennc

**Comment by BrennanConroy** [comment]
VSCode seems to be in its own environment and whatever that is doesn't include APPDATA

**Comment by muratg** [comment]
@glennc Could we check with VSCode folks?

**Comment by BrennanConroy** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/21

**Comment by muratg** [comment]
Moving to 1.0.1 to keep track of the OmniSharp change.

**Comment by BrennanConroy** [comment]
Can't repro this anymore, looks like it has been fixed.
